### ISSUE TITLE
Need support for HeaderFilter and BodyFilter phases

### ISSUE THREAD

**Issue by 0angelic0** [Kong/go-pdk#197] opened 2024-04-02 01:41 UTC
Need support for HeaderFilter and BodyFilter phases.

Since I use serverless plugin (AWS Lambda) and the plugin's Response phase is not called. But from a lua plugin header_filter and body_filter will be called. So, I need go plugin to support HeaderFilter and BodyFilter phases as well.

Thank you.

**Comment by gszr** [comment] 2024-04-09 20:21
Hi @0angelic0,

Thanks for opening this issue and welcome to the Kong community.

The `header_filter` and `body_filter` phases do not support the socket API Kong uses to communicate with the pluginserver; this is a known limitation, by design. 

The goal of the Go PDK is not to replace the Lua PDK entirely, but to allow you to tap in tap into the Go ecosystem when there isn't a Lua equivalent available; therefore, we recommend you to write your plugin in Lua if it's paramount to use the header and body filters.

We have a planned task to improve out docs and make this (and other) limitations clearer.

As always, happy to answer questions. For now, I will leave this issue open.

Happy Konging! 🦍

**Comment by jschmid1** [comment] 2024-04-15 07:07
Answered, closing.

**Closed by jschmid1** 2024-04-15 07:07 UTC
Labels: enhancement
