### ISSUE TITLE
socket failed: No such file or directory

### ISSUE THREAD

**Issue by kurosawa93** [Kong/go-pdk#151] opened 2023-07-04 10:24 UTC
I have encountered these error when i want to migrate the kong instance to the latest version:

```
kong-kong-ce-1  | 2023/07/04 06:27:19 [debug] 1#0: [kong] process.lua:66 search config for pluginserver named: kong-apm-plugin
kong-kong-ce-1  | 2023/07/04 06:27:19 [debug] 1#0: [lua] plugins.lua:284: load_plugin(): Loading plugin: kong-apm-plugin
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1135#0: *436 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1138#0: *474 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1136#0: *499 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1141#0: *713 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1140#0: *963 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1149#0: *1074 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1143#0: *1140 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1146#0: *1497 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1148#0: *1585 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1139#0: *1623 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1147#0: *1799 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1142#0: *1830 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1144#0: *2127 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [notice] 1134#0: *2141 [kong] process.lua:252 Starting kong-apm-plugin, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1137#0: *2251 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1134#0: *2253 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [crit] 1145#0: *2401 connect() to unix:/usr/local/kong/kong-apm-plugin.socket failed (2: No such file or directory), context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 Listening on socket: /usr/local/kong/kong-apm-plugin.socket, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
kong-kong-ce-1  | 2023/07/04 06:27:20 [info] 1134#0: *2141 [kong-apm-plugin:1150] 2023/07/04 06:27:20 EOF, context: ngx.timer
```

the plugin works fine in Kong version 3.0 or below, but not working in version 3.1.0 and above. If i run the binary indepedently, looks like working fine
```
bash-5.1$ ./kong-apm-plugin -dump
{"Protocol":"ProtoBuf:1","SocketPath":"/usr/local/kong/kong-apm-plugin.socket","Plugins":[{"Name":"kong-apm-plugin","Phases":["access"],"Version":"1.0.0","Priority":-1,"Schema":{"name":"kong-apm-plugin","fields":[{"config":{"type":"record""fields":[]}}]}}]}
```

Is it related to Kong dropping support for legacy hybrid configuration protocol?

**Comment by StarlightIbuki** [comment] 2023-08-31 09:20
Could you share the config of Kong for the plugin server?

**Comment by wangcong791510428** [comment] 2023-09-11 11:51
the same question

**Comment by StarlightIbuki** [comment] 2023-09-12 09:23
The `critical` message is emitted when Kong tries to test if the plugin server is ready (the socket is accessible) so it's expected. It cannot be silenced due to the limitation of OpenResty. You may try the latest version, which removes the detection logic.

> The same question

@wangcong791510428 Are you using the same versions as @kurosawa?

**Comment by wangcong791510428** [comment] 2023-09-12 10:12
docker run --restart=always --network=kong-net -d --name kong --log-opt max-size=50m --log-opt max-file=3  --log-driver json-file \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_DATABASE=********" \
-e "KONG_PG_PASSWORD=************" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_PLUGINS=bundled,ubm-auth-go" \
-e "KONG_PLUGINSERVER_NAMES=ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_START_CMD=/usr/local/bin/ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_QUERY_CMD=/usr/local/bin/ubm-auth-go -dump" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_SOCK=/usr/local/kong/ubm-auth-go.sock" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8002, 0.0.0.0:8444 ssl" \
-v "path/kong-ratelimit-go/ubm-auth-go:/usr/local/bin/ubm-auth-go" \
-p 8000:8000 \
-p 5001:8443 \
-p 8002:8002 \
-p 8444:8444 kong:3.4

**Comment by wangcong791510428** [comment] 2023-09-12 10:13
docker run --restart=always --network=kong-net -d --name kong --log-opt max-size=50m --log-opt max-file=3  --log-driver json-file \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_DATABASE=kong" \
-e "KONG_PG_PASSWORD=kongPg0907" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_PLUGINS=bundled,ubm-auth-go" \
-e "KONG_PLUGINSERVER_NAMES=ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_START_CMD=/usr/local/bin/ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_QUERY_CMD=/usr/local/bin/ubm-auth-go -dump" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_SOCK=/usr/local/kong/ubm-auth-go.sock" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8002, 0.0.0.0:8444 ssl" \
-v "/data/bigmodel/kong/make-image/kong-ratelimit-go/ubm-auth-go:/usr/local/bin/ubm-auth-go" \
-p 8000:8000 \
-p 5001:8443 \
-p 8002:8002 \
-p 8444:8444 kong:3.4

**Comment by wangcong791510428** [comment] 2023-09-12 10:14
docker run --restart=always --network=kong-net -d --name kong --log-opt max-size=50m --log-opt max-file=3  --log-driver json-file \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-database" \
-e "KONG_PG_USER=kong" \
-e "KONG_PG_DATABASE=kong" \
-e "KONG_PG_PASSWORD=kongPg0907" \
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
-e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
-e "KONG_PLUGINS=bundled,ubm-auth-go" \
-e "KONG_PLUGINSERVER_NAMES=ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_START_CMD=/usr/local/bin/ubm-auth-go" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_QUERY_CMD=/usr/local/bin/ubm-auth-go -dump" \
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_SOCK=/usr/local/kong/ubm-auth-go.sock" \
-e "KONG_ADMIN_LISTEN=0.0.0.0:8002, 0.0.0.0:8444 ssl" \
-v "/data/bigmodel/kong/make-image/kong-ratelimit-go/ubm-auth-go:/usr/local/bin/ubm-auth-go" \
-p 8000:8000 \
-p 5001:8443 \
-p 8002:8002 \
-p 8444:8444 kong:3.4

the complete docker  commond

**Comment by wangcong791510428** [comment] 2023-09-12 10:15
docker run --restart=always --network=kong-net -d --name kong --log-opt max-size=50m --log-opt max-file=3 --log-driver json-file
-e "KONG_DATABASE=postgres"
-e "KONG_PG_HOST=kong-database"
-e "KONG_PG_USER=kong"
-e "KONG_PG_DATABASE=kong"
-e "KONG_PG_PASSWORD=****"
-e "KONG_PROXY_ACCESS_LOG=/dev/stdout"
-e "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
-e "KONG_PROXY_ERROR_LOG=/dev/stderr"
-e "KONG_ADMIN_ERROR_LOG=/dev/stderr"
-e "KONG_PLUGINS=bundled,ubm-auth-go"
-e "KONG_PLUGINSERVER_NAMES=ubm-auth-go"
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_START_CMD=/usr/local/bin/ubm-auth-go"
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_QUERY_CMD=/usr/local/bin/ubm-auth-go -dump"
-e "KONG_PLUGINSERVER_UBM_AUTH_GO_SOCK=/usr/local/kong/ubm-auth-go.sock"
-e "KONG_ADMIN_LISTEN=0.0.0.0:8002, 0.0.0.0:8444 ssl"
-v "/data/bigmodel/kong/make-image/kong-ratelimit-go/ubm-auth-go:/usr/local/bin/ubm-auth-go"
-p 8000:8000
-p 5001:8443
-p 8002:8002
-p 8444:8444 kong:3.4

the complete docker commond but i use kong:2.7 work ok

**Comment by wangcong791510428** [comment] 2023-09-12 10:17
when i use kong:3.4  the result the same question  kurosawa93

**Comment by StarlightIbuki** [comment] 2023-10-08 09:35
@wangcong791510428 Could you confirm if that socket file exists?
The auto-generated socket should be named with postfix ".socket": https://github.com/Kong/go-pdk/blob/231514d03815a92c9f502211fa1d82bd7e54b1e0/server/os.go#L44

**Comment by alt-dima** [comment] 2024-02-05 11:39
We have same issue with custom go-plugin
```
│ 2024/02/04 12:23:24 [crit] 1262#0: *302 connect() to unix:/usr/local/kong/okta-token-verifier-multi-auth.socket failed (2: No such file or directory), context: ngx.timer                                                                       │
│ 2024/02/04 12:23:25 [notice] 1262#0: *157 [lua] warmup.lua:70: finished warming up DNS entries' into the cache (in 897ms), context: ngx.timer                                                                                                   │
│ 2024/02/04 13:16:40 [warn] 1262#0: *5114 [kong] mp_rpc.lua:157 [okta-token-verifier-multi-auth] [OTV-GO-PLUGIN] 
```
checked file
```
kong-app-v2-5f947879dc-mkjwb:/usr/local/opt/lua-plugins$ cd /usr/local/kong/
kong-app-v2-5f947879dc-mkjwb:/usr/local/kong$ ls -la | grep okta
srwxr-xr-x    1 kong     nogroup          0 Feb  4 12:23 okta-token-verifier-multi-auth.socket
```
Seems kong checks, tries to connect to socket before plugin started

**Comment by StarlightIbuki** [comment] 2024-02-19 02:38
> We have same issue with custom go-plugin
> 
> ```
> │ 2024/02/04 12:23:24 [crit] 1262#0: *302 connect() to unix:/usr/local/kong/okta-token-verifier-multi-auth.socket failed (2: No such file or directory), context: ngx.timer                                                                       │
> │ 2024/02/04 12:23:25 [notice] 1262#0: *157 [lua] warmup.lua:70: finished warming up DNS entries' into the cache (in 897ms), context: ngx.timer                                                                                                   │
> │ 2024/02/04 13:16:40 [warn] 1262#0: *5114 [kong] mp_rpc.lua:157 [okta-token-verifier-multi-auth] [OTV-GO-PLUGIN] 
> ```
> 
> checked file
> 
> ```
> kong-app-v2-5f947879dc-mkjwb:/usr/local/opt/lua-plugins$ cd /usr/local/kong/
> kong-app-v2-5f947879dc-mkjwb:/usr/local/kong$ ls -la | grep okta
> srwxr-xr-x    1 kong     nogroup          0 Feb  4 12:23 okta-token-verifier-multi-auth.socket
> ```
> 
> Seems kong checks, tries to connect to socket before plugin started

It's expected for Kong to print error messages when starting plugin servers. As soon as the plugin server is started it should work.

**Comment by gszr** [comment] 2024-02-21 23:49
As explained by @StarlightIbuki, notice that the errors stop after the plugin with its server is started. Closing this issue for now; if you encounter issues in more recent Kong versions, please open a new ticket, with logs, reproduction steps, Kong version, and configuration

**Closed by gszr** 2024-02-21 23:49 UTC
