### ISSUE TITLE
go-plugin can't get ctx set by lua

### ISSUE THREAD

**Issue by two** [Kong/go-pdk#47] opened 2020-10-03 08:15 UTC
lua plugin at `body_filter` phase:
```lua
local function status()
        local s = kong.response.get_status()
        kong.ctx.shared.status = s
end
```
go plugin at `log` phase:
```go
func (conf Config) Log(kong *pdk.PDK) {

        status, err := kong.Ctx.GetSharedInt("status")
        if err!= nil {
                kong.Log.Err(err.Error())
        }
       ....
}
```
got error : `null response`

**Comment by PFadel** [comment] 2020-10-21 18:14
Same error here, any response about this ?

**Comment by fffonion** [comment] 2021-03-29 10:31
I can't reproduce the issue locally, which version of Kong and pluginserver are you using?

**Comment by javierguerragiraldez** [comment] 2021-04-14 17:28
There have been several fixes and refactors around this code.  Closing for now as I don't think it's about a recent version, please reopen if the issue still exists.

**Closed by javierguerragiraldez** 2021-04-14 17:28 UTC
Labels: pending author feedback
