### ISSUE TITLE
Authenticate method now requires consumer AND credential

### ISSUE THREAD

**Issue by HairyMike** [Kong/go-pdk#96] opened 2022-03-14 15:12 UTC
I can see that this [code block](https://github.com/Kong/go-pdk/blob/master/client/client.go#L130-L135) was added under [this commit](https://github.com/Kong/go-pdk/commit/367be2a789dc8185e3ce54328b70533e63e419fc).

Previously it would have been ok to authenticate with either consumer or credential.  Is this change intentional?  Could the comments be updated to reflect the new requirements?

I can see that creating an empty `AuthenticatedCredential` gets past this validation:
```
credential := client.AuthenticatedCredential{}
if err := kong.Client.Authenticate(&consumer, &credential); err != nil {
	handleError(fmt.Errorf("authenticate consumer (%v) failed: %s", consumer, err), kong)
	return
}
```

Many thanks

**Comment by gszr** [comment] 2024-02-22 00:38
Thank you for the report; you are right, they can be `nil`. Closing this as a duplicate of https://github.com/Kong/go-pdk/issues/152.

**Closed by gszr** 2024-02-22 00:38 UTC
